[package]
name = "raytrace"
version = "0.1.0"
authors = ["Florian Schmiderer <florian.schmiderer@yahoo.de>"]
edition = "2018"

[dependencies]
mini_gl_fb = "0.6.0"
nalgebra = "0.16.0"
ncollide3d = "0.17.0"
